config/routes.rb
Rails.application.routes.draw do
  # root to:
  get 'decodings/index'

  get 'decodings/new'

  get 'decoding/show'

  post 'decodings/show'

  get 'encodings/index'

  get 'encodings/new'

  post 'encodings/show'

  get 'encodings/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/decodings_controller.rb
class DecodingsController < ApplicationController
  
  skip_before_filter :verify_authenticity_token

  def index
  end

  def new
  end

  def show
    @message = Caesar.decode(params[:shift], params[:message].upcase)
  end
end

app/controllers/encodings_controller.rb
class EncodingsController < ApplicationController
 
  skip_before_filter :verify_authenticity_token

  def index
    
  end

  def new
  end

  def show
    @message = Caesar.encode(params[:shift], params[:message])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decodings_helper.rb
module DecodingsHelper
end

app/helpers/encodings_helper.rb
module EncodingsHelper
end

app/views/decodings/index.html.erb
<h1>Decodings#index</h1>
<p><%= link_to "Decode a Message", decodings_new_path  %></p>

app/views/decodings/new.html.erb
<h1>Decode a Message</h1>

<form action="show" method="post" accept-charset=""utf-8>

  <label for="shift"> Letter To Offset By: </label>
  <input type="text" name="shift" id="shift">

  <label for="message"> Your message </label>
  <input type="text" name="message" id="message">

  <input type="submit" value="Decode!">


</form>

app/views/decodings/show.html.erb
<h1>Here Is Your Decoded Message!</h1>
<p><%= @message %></p>

app/views/encodings/index.html.erb
<h1>Encodings#index</h1>
<p><%= link_to "Encode a Message", encodings_new_path  %></p>

app/views/encodings/new.html.erb
<h1>Encode a Message</h1>

<form action="show" method="post" accept-charset=""utf-8>

  <label for="shift"> Letter To Offset By: </label>
  <input type="text" name="shift" id="shift">

  <label for="message"> Your message </label>
  <input type="text" name="message" id="message">

  <input type="submit" value="Encode!">


</form>

app/views/encodings/show.html.erb
<h1>Encodings#show</h1>
<p><%= @message %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaesarCipher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>